import { db } from "@/src/prisma/db";
export type MessageTemplate = "sale_confirmation"|"invoice"|"payment_confirmation"|"payment_reminder";
const templates:Record<MessageTemplate,(v:Record<string,string|number>)=>string>={
 sale_confirmation:v=>`Hafiz Retail POS: Sale ${v.invoiceNumber} confirmed. Total ${v.total}. Paid ${v.paid}. Remaining ${v.remaining}.`,
 invoice:v=>`Invoice ${v.invoiceNumber}: Total ${v.total}, Paid ${v.paid}, Remaining ${v.remaining}. Thank you.`,
 payment_confirmation:v=>`Payment received: ${v.amount}. Remaining balance: ${v.remaining}. Thank you.`,
 payment_reminder:v=>`Payment reminder: your remaining balance is ${v.remaining}. Please contact us for payment details.`
};
function normalizePhone(p:string){return p.replace(/[^0-9+]/g,"");}
async function log(channel:string,recipient:string,template:string,message:string,status:string,providerId="",error=""){try{await db.orm.public.MessageLog.create({channel,recipient,template,message,status,providerId,error});}catch(e){console.error("Message log failed",e)}}
async function whatsapp(to:string,message:string,template:string){const token=process.env.WHATSAPP_ACCESS_TOKEN,id=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!id)throw new Error("WhatsApp credentials are not configured.");const res=await fetch(`https://graph.facebook.com/v22.0/${id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:typePhone(to),type:"text",text:{body:message}})});const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||"WhatsApp send failed");const providerId=data?.messages?.[0]?.id||"";await log("WHATSAPP",to,template,message,"SENT",providerId);return providerId}
function typePhone(v:string){return normalizePhone(v).replace(/^\+/,"")}
async function sms(to:string,message:string,template:string){const url=process.env.SMS_API_URL,key=process.env.SMS_API_KEY;if(!url||!key)throw new Error("SMS provider is not configured.");const res=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({to:normalizePhone(to),message})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.message||"SMS send failed");const providerId=String(data?.id||data?.messageId||"");await log("SMS",to,template,message,"SENT",providerId);return providerId}
export async function sendBusinessMessage(input:{to:string;template:MessageTemplate;values:Record<string,string|number>;fallbackToSms?:boolean}){const to=normalizePhone(input.to);if(!to)return {success:false,error:"Recipient phone is required."};const message=templates[input.template](input.values);try{const id=await whatsapp(to,message,input.template);return {success:true,channel:"WHATSAPP",providerId:id};}catch(e){await log("WHATSAPP",to,input.template,message,"FAILED","",e instanceof Error?e.message:"Failed");if(input.fallbackToSms!==false){try{const id=await sms(to,message,input.template);return {success:true,channel:"SMS",providerId:id};}catch(s){await log("SMS",to,input.template,message,"FAILED","",s instanceof Error?s.message:"Failed");return {success:false,error:s instanceof Error?s.message:"Failed"}}}return {success:false,error:e instanceof Error?e.message:"Failed"}}
