"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import ReturnModal from "./ReturnModal";
import type { ReturnRecord, ReturnStatus } from "./returnTypes";
import { money, statusClass } from "./returnUtils";

export default function ReturnsPage(){
 const [returns,setReturns]=useState<ReturnRecord[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[status,setStatus]=useState<"All"|ReturnStatus>("All");const[editing,setEditing]=useState<ReturnRecord|null>(null);const[show,setShow]=useState(false);const[selected,setSelected]=useState<ReturnRecord|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);const r=await fetch("/api/returns",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load returns.");setReturns(d.returns||[])}catch(e){alert(e instanceof Error?e.message:"Failed to load returns.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const t=search.toLowerCase().trim();return returns.filter(x=>(!t||x.returnNo.toLowerCase().includes(t)||x.invoiceNo.toLowerCase().includes(t)||x.customerName.toLowerCase().includes(t)||x.items.some(i=>i.productName.toLowerCase().includes(t)))&&(status==="All"||x.status===status))},[returns,search,status]);
 const stats={total:returns.length,completed:returns.filter(x=>x.status==="Completed").length,pending:returns.filter(x=>x.status==="Pending").length,refunds:returns.reduce((s,x)=>s+x.refundAmount,0)};
 async function remove(x:ReturnRecord){if(!confirm(`Delete ${x.returnNo}? Completed return delete karne par restored stock rollback hoga.`))return;const r=await fetch(`/api/returns/${x.id}`,{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok)return alert(d.error||"Unable to delete return.");await load()}
 return <div className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
 <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-2xl font-bold">Returns</h1><p className="mt-1 text-sm text-slate-500">Invoice-based returns, refunds and stock restoration.</p></div><button onClick={()=>{setEditing(null);setShow(true)}} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">+ New Return</button></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Returns",stats.total],["Completed",stats.completed],["Pending",stats.pending],["Total Refunds",money(stats.refunds)]].map(([a,b])=><div key={a} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-xl font-bold">{b}</p></div>)}</div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search return, invoice, customer, product..." className="rounded-xl border bg-slate-50 px-4 py-3"/><select value={status} onChange={e=>setStatus(e.target.value as any)} className="rounded-xl border bg-slate-50 px-4 py-3">{["All","Pending","Approved","Completed","Rejected"].map(x=><option key={x}>{x}</option>)}</select><div className="rounded-xl bg-slate-50 px-4 py-3 text-sm">Showing <b>{filtered.length}</b> returns</div></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[1050px]"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Return","Invoice","Customer","Product","Amount","Refund","Status","Actions"].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-12 text-center">Loading...</td></tr>:filtered.length===0?<tr><td colSpan={8} className="p-12 text-center">No returns found.</td></tr>:filtered.map(x=><tr key={x.id} className="border-t hover:bg-slate-50"><td className="px-5 py-4"><b>{x.returnNo}</b><div className="text-xs text-slate-500">{new Date(x.date).toLocaleString("en-PK")}</div></td><td className="px-5 py-4">{x.invoiceNo}</td><td className="px-5 py-4">{x.customerName}</td><td className="px-5 py-4">{x.items.map(i=>i.productName).join(", ")}</td><td className="px-5 py-4 font-bold">{money(x.totalAmount)}</td><td className="px-5 py-4">{money(x.refundAmount)}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(x.status)}`}>{x.status}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={()=>setSelected(x)} className="rounded-lg border px-3 py-2 text-xs font-bold">View</button><button onClick={()=>{setEditing(x);setShow(true)}} className="rounded-lg border px-3 py-2 text-xs font-bold">Edit</button><button onClick={()=>void remove(x)} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-600">Delete</button></div></td></tr>)}</tbody></table></div></div>
 </div>{show&&<ReturnModal record={editing} onClose={()=>{setShow(false);setEditing(null)}} onSaved={load}/>} {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">{selected.returnNo}</h2><p className="mt-2">Invoice: {selected.invoiceNo}</p><p>Customer: {selected.customerName}</p><p>Refund: {money(selected.refundAmount)}</p><p>Status: {selected.status}</p><p className="mt-3 rounded-xl bg-slate-50 p-3">{selected.reason||"No reason"}</p><button onClick={()=>setSelected(null)} className="mt-5 w-full rounded-xl bg-slate-900 p-3 font-bold text-white">Close</button></div></div>}</div>
}
