"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { LockKeyhole, Mail, UserRound } from "lucide-react";

export default function LoginPage(){
 const router=useRouter(); const [setup,setSetup]=useState(false); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
 const [name,setName]=useState("Super Admin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
 useEffect(()=>{fetch("/api/auth/setup").then(r=>r.json()).then(d=>setSetup(Boolean(d.setupRequired))).catch(()=>{});},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const res=await fetch(setup?"/api/auth/setup":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});const data=await res.json();if(!res.ok){setMessage(data.message||"Unable to login.");return;}router.replace("/dashboard");router.refresh();}catch{setMessage("Server connection failed.");}finally{setLoading(false)}}
 return <main className="min-h-screen bg-slate-100 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl bg-white border border-slate-200 shadow-xl p-8"><div className="mb-7"><div className="h-12 w-12 rounded-xl bg-slate-900 text-white flex items-center justify-center mb-4"><LockKeyhole size={24}/></div><h1 className="text-2xl font-bold text-slate-900">Hafiz Retail POS</h1><p className="text-sm text-slate-500 mt-1">{setup?"First-time Super Admin setup":"Sign in to continue"}</p></div><form onSubmit={submit} className="space-y-4">{setup&&<label className="block"><span className="text-sm font-medium">Name</span><div className="mt-1 flex items-center border rounded-lg px-3"><UserRound size={17}/><input className="w-full p-3 outline-none" value={name} onChange={e=>setName(e.target.value)} required/></div></label>}<label className="block"><span className="text-sm font-medium">Email</span><div className="mt-1 flex items-center border rounded-lg px-3"><Mail size={17}/><input type="email" className="w-full p-3 outline-none" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div></label><label className="block"><span className="text-sm font-medium">Password</span><div className="mt-1 flex items-center border rounded-lg px-3"><LockKeyhole size={17}/><input type="password" className="w-full p-3 outline-none" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete={setup?"new-password":"current-password"}/></div></label>{message&&<p className="text-sm text-red-600 bg-red-50 rounded-lg p-3">{message}</p>}<button disabled={loading} className="w-full rounded-lg bg-slate-900 text-white py-3 font-semibold disabled:opacity-60">{loading?"Please wait...":setup?"Create Admin & Login":"Login"}</button>{setup&&<p className="text-xs text-slate-500">Password: minimum 8 characters with at least one letter and one number.</p>}</form></div></main>
}
